# Generated by Django 3.2.6 on 2021-08-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(default=None, verbose_name='User info'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default=None, upload_to='images', verbose_name='User profile photo'),
        ),
    ]
