# Generated by Django 3.2.6 on 2021-08-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210808_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, verbose_name='User info'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='User profile photo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to='users.UserSubscribers'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='users.UserSubscriptions'),
        ),
    ]
